# Docker Profile Configuration

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:cms_db}

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: auth-service
    prefer-ip-address: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

permission:
  base-url: http://access-management-service

